### ISSUE TITLE
fix node-icu-charset-detector issue, when user npm install. 

### ISSUE THREAD

**Issue by omgbox** [penandlim/Heroku-XDCC#2]
the error 

`npm ERR! path /root/Heroku-XDCC/node_modules/node-icu-charset-detector
`

the fix

> NODE_PATH=../node_modules npm install node-icu-charset-detector

works
debian 8 64
nodev10.16.0
npm 6.9.0

**Comment by penandlim** [comment]
Changed irc package to https://github.com/Throne3d/node-irc
node-icu-charset-detector is not a requirement anymore.
